<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-12-05">

<title>Waterfowl - LTEM - Yellow Point</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="waterfowl-single-site_files/libs/clipboard/clipboard.min.js"></script>
<script src="waterfowl-single-site_files/libs/quarto-html/quarto.js"></script>
<script src="waterfowl-single-site_files/libs/quarto-html/popper.min.js"></script>
<script src="waterfowl-single-site_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="waterfowl-single-site_files/libs/quarto-html/anchor.min.js"></script>
<link href="waterfowl-single-site_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="waterfowl-single-site_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="waterfowl-single-site_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="waterfowl-single-site_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="waterfowl-single-site_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary-of-waterfowl-ltem-protocol" id="toc-summary-of-waterfowl-ltem-protocol" class="nav-link active" data-scroll-target="#summary-of-waterfowl-ltem-protocol"> <span class="header-section-number">1</span> Summary of Waterfowl LTEM protocol</a>
  <ul class="collapse">
  <li><a href="#basic-protocol" id="toc-basic-protocol" class="nav-link" data-scroll-target="#basic-protocol"> <span class="header-section-number">1.1</span> Basic protocol</a></li>
  <li><a href="#cautions-about-the-protocol." id="toc-cautions-about-the-protocol." class="nav-link" data-scroll-target="#cautions-about-the-protocol."> <span class="header-section-number">1.2</span> Cautions about the protocol.</a>
  <ul class="collapse">
  <li><a href="#dont-use-0-to-indicate-a-missing-value." id="toc-dont-use-0-to-indicate-a-missing-value." class="nav-link" data-scroll-target="#dont-use-0-to-indicate-a-missing-value."> <span class="header-section-number">1.2.1</span> Don’t use 0 to indicate a missing value.</a></li>
  <li><a href="#classifying-by-season" id="toc-classifying-by-season" class="nav-link" data-scroll-target="#classifying-by-season"> <span class="header-section-number">1.2.2</span> Classifying by season</a></li>
  </ul></li>
  <li><a href="#database-structure" id="toc-database-structure" class="nav-link" data-scroll-target="#database-structure"> <span class="header-section-number">1.3</span> Database structure</a></li>
  </ul></li>
  <li><a href="#reading-and-checking-the-data" id="toc-reading-and-checking-the-data" class="nav-link" data-scroll-target="#reading-and-checking-the-data"> <span class="header-section-number">2</span> Reading and checking the data</a>
  <ul class="collapse">
  <li><a href="#variables-names-corrected-for-r" id="toc-variables-names-corrected-for-r" class="nav-link" data-scroll-target="#variables-names-corrected-for-r"> <span class="header-section-number">2.1</span> Variables names corrected for <em>R</em></a></li>
  <li><a href="#dates-converted-to-standardized-form" id="toc-dates-converted-to-standardized-form" class="nav-link" data-scroll-target="#dates-converted-to-standardized-form"> <span class="header-section-number">2.2</span> Dates converted to standardized form</a></li>
  <li><a href="#checking-study-area-name" id="toc-checking-study-area-name" class="nav-link" data-scroll-target="#checking-study-area-name"> <span class="header-section-number">2.3</span> Checking Study Area Name</a></li>
  <li><a href="#checking-station-codes" id="toc-checking-station-codes" class="nav-link" data-scroll-target="#checking-station-codes"> <span class="header-section-number">2.4</span> Checking Station codes</a></li>
  <li><a href="#checking-species-code" id="toc-checking-species-code" class="nav-link" data-scroll-target="#checking-species-code"> <span class="header-section-number">2.5</span> Checking species code</a></li>
  </ul></li>
  <li><a href="#single-site-analysis" id="toc-single-site-analysis" class="nav-link" data-scroll-target="#single-site-analysis"> <span class="header-section-number">3</span> Single Site Analysis</a>
  <ul class="collapse">
  <li><a href="#maximum-counts" id="toc-maximum-counts" class="nav-link" data-scroll-target="#maximum-counts"> <span class="header-section-number">3.1</span> Maximum counts</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"> <span class="header-section-number">4</span> Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"> <span class="header-section-number">5</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Waterfowl - LTEM - Yellow Point</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 5, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="summary-of-waterfowl-ltem-protocol" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Summary of Waterfowl LTEM protocol</h1>
<section id="basic-protocol" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="basic-protocol"><span class="header-section-number">1.1</span> Basic protocol</h2>
<p>As taken from the protocol document:</p>
<blockquote class="blockquote">
<p>“Establish observation points at enough sites to provide views of the entire survey area. …</p>
<p>Choose a date after which migrants are mostly gone. Count on 3 separate occasions during a 2-3 week period and keep &gt; highest count.”</p>
</blockquote>
<p>The data collected under this protocol at each survey consists of the following variables:</p>
<ul>
<li>Species. The species of waterfowl counted.</li>
<li>Sex. The sex of the species.</li>
<li>Count. The number of birds of this species and sex. Choose a date after which migrants are mostly gone</li>
</ul>
</section>
<section id="cautions-about-the-protocol." class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="cautions-about-the-protocol."><span class="header-section-number">1.2</span> Cautions about the protocol.</h2>
<section id="dont-use-0-to-indicate-a-missing-value." class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="dont-use-0-to-indicate-a-missing-value."><span class="header-section-number">1.2.1</span> Don’t use 0 to indicate a missing value.</h3>
<p>If no species were seen during a visit, this is indicated by the species code being set to missing and the count field being set to 0. This needs to be done consistently over time.</p>
<p>If no visit was made to a station, then there are no records in the <em>General Survey</em> worksheet. One must infer that if there are no records for a station at a date, that it was not visited. The <em>Sample Station Information</em> worksheet only has information on the station label and not when they were visited. It is preferable to include in this sheet the visit dates of each station in that year explicitly rather than trying to infer this information from the <em>General Survey</em> worksheet.</p>
</section>
<section id="classifying-by-season" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="classifying-by-season"><span class="header-section-number">1.2.2</span> Classifying by season</h3>
<p>The protocol is silent about seasonal sampling, e.g., spring vs.&nbsp;fall. There is some issue on how to properly pool information that is close together but crosses year boundaries. For example, surveys may be done in late December of 2013 and early January of 2014. If the maximum counts over multiple visits in the winter are collected, visits on these two months need to be “combined” even though they are in different calendar years.</p>
<p>For this analysis we classified by month (November, December, January, February) to avoid this problem</p>
</section>
</section>
<section id="database-structure" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="database-structure"><span class="header-section-number">1.3</span> Database structure</h2>
<p>The database for this protocol is a series of Excel workbooks with multiple sheets in each workbook. The <em>Sample Station Information</em> sheet contains the information on the stations available for this year. If a station is not visited, this is indicated by a missing record in the <em>General Survey</em> worksheet. The <em>General Survey</em> sheet contains the information collected. There are multiple lines per visit. If a visit was done but no birds were seen, then the species code is set to missing with a count of 0.</p>
<p>The relevant fields on the <em>General Survey</em> worksheet are:</p>
<ul>
<li><em>Sample Location Label</em>. **Appears to be changed to Transect Label starting in 2019.</li>
<li><em>Date</em>. The date the data was collected. The <em>Year</em> is extracted from this date.</li>
<li><em>Species</em>. What species were seen</li>
<li><em>Count</em>. Count of the number of birds of each species.</li>
</ul>
</section>
</section>
<section id="reading-and-checking-the-data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Reading and checking the data</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>

**Extracting the following sheets  General Survey 
      From  wsi_5516_dct_2013YellowPointWaterbird.xlsm 
      From  wsi_5516_dct_2014Yellowpoint.xls 
      From  wsi_5516_dct_2015Yellowpoint.xls 
      From  wsi_5516_dct_2016Yellowpoint.xls 
      From  wsi_5516_dct_2017Yellowpoint.xls 
      From  wsi_5516_dct_2019Yellowpoint.xlsm 
      From  wsi_5516_dct_2020Yellowpoint.xlsm </code></pre>
</div>
</div>
<p>The database was read for all record pertaining to the Yellow Point. The following files were found for this site:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>File names with the data </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "wsi_5516_dct_2013YellowPointWaterbird.xlsm"
[2] "wsi_5516_dct_2014Yellowpoint.xls"          
[3] "wsi_5516_dct_2015Yellowpoint.xls"          
[4] "wsi_5516_dct_2016Yellowpoint.xls"          
[5] "wsi_5516_dct_2017Yellowpoint.xls"          
[6] "wsi_5516_dct_2019Yellowpoint.xlsm"         
[7] "wsi_5516_dct_2020Yellowpoint.xlsm"         </code></pre>
</div>
</div>
<div class="cell">

</div>
<p>Notice we needed to fix the <em>Sample Station Label</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice that Sample.station.label was changed to Transect.Label starting in 2018?</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>select <span class="ot">&lt;-</span> <span class="fu">is.na</span>(waterfowl.df<span class="sc">$</span><span class="st">"Sample Station Label"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>waterfowl.df<span class="sc">$</span><span class="st">"Sample Station Label"</span>[select] <span class="ot">&lt;-</span> waterfowl.df<span class="sc">$</span><span class="st">"Transect Label"</span>[select]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The following data editing was performed</p>
<section id="variables-names-corrected-for-r" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="variables-names-corrected-for-r"><span class="header-section-number">2.1</span> Variables names corrected for <em>R</em></h2>
<p>Variable names in <em>R</em> must start with a letter and contain letters or numbers or underscores. Blanks in variable names are not normally allowed, nor are special characters such as %. These are normally replaced by periods (“.”) in the variable name.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Original variable names in data frame</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Study area name"                            
 [2] "Sample station label"                       
 [3] "Date"                                       
 [4] "Time"                                       
 [5] "End time"                                   
 [6] "Surveyor"                                   
 [7] "Species"                                    
 [8] "Count"                                      
 [9] "Survey observation photos"                  
[10] "Animal id"                                  
[11] "Utm zone"                                   
[12] "Easting"                                    
[13] "Northing"                                   
[14] "Comments"                                   
[15] "Inventory method"                           
[16] "Spatial accuracy (m)"                       
[17] "Detect type"                                
[18] "Detect direction (deg)"                     
[19] "Detect distance (m)"                        
[20] "Temporary animal id"                        
[21] "Life stage"                                 
[22] "Sex"                                        
[23] "Behaviour"                                  
[24] "Feature type"                               
[25] "Feature label"                              
[26] "Feature count"                              
[27] "Sign type"                                  
[28] "Sign or sample age"                         
[29] "Sign count"                                 
[30] "Group label"                                
[31] "Adult males"                                
[32] "Adult females"                              
[33] "Adults - unclassified sex"                  
[34] "Juvenile males"                             
[35] "Juvenile females"                           
[36] "Juveniles - unclassified sex"               
[37] "Males - unclassified life stage"            
[38] "Females - unclassified life stage"          
[39] "Unclassified life stage and sex"            
[40] "Eggs"                                       
[41] "Egg masses"                                 
[42] "Larvae"                                     
[43] "Pupae"                                      
[44] "Hatchlings"                                 
[45] "Fledglings"                                 
[46] "Add your new field here"                    
[47] "Traps sprung"                               
[48] "No of visits or samples"                    
[49] "Nights trapped"                             
[50] "Distance covered (km)"                      
[51] "Design component visit comments"            
[52] "Design component visit photos"              
[53] "Design component visit photo comments"      
[54] "Sampling condition type"                    
[55] "Sc datetime"                                
[56] "Air temp (c)"                               
[57] "Prec 48 hr air temp (c)"                    
[58] "Wind speed"                                 
[59] "Wind direction"                             
[60] "Prec 48 hr wind speed"                      
[61] "Current precipitation"                      
[62] "Rainfall over 24 hours (mm)"                
[63] "Rainfall over 48 hours (mm)"                
[64] "Prec 48 hr precip"                          
[65] "Cloud type"                                 
[66] "Cloud cover"                                
[67] "Cloud ceiling"                              
[68] "Prec 48 hr cloud cover"                     
[69] "Snow depth"                                 
[70] "Snow cover"                                 
[71] "Time since 5 cm snow"                       
[72] "Water temperature (c)"                      
[73] "Sea wind condition"                         
[74] "Sea surface temperature (c)"                
[75] "Sea surface salinity (ppt)"                 
[76] "Swell height (m)"                           
[77] "Wavelet height (cm)"                        
[78] "Tide direction"                             
[79] "Ground temperature (c)"                     
[80] "Ground moisture"                            
[81] "Leaf moisture"                              
[82] "Official sunrise"                           
[83] "Lunar phase"                                
[84] "Turbidity (cm)"                             
[85] "Temperature variance"                       
[86] "Sampling condition comments"                
[87] "workbook"                                   
[88] "Reliable observer"                          
[89] "Quality observation"                        
[90] "Additional notes"                           
[91] "Transect label"                             
[92] "Additional predefined transect visit fields"
[93] "Predefined sampling condition fields"       
[94] "Description precipitation"                  </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Corrected variable names of data frame</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Study.area.name"                            
 [2] "Sample.station.label"                       
 [3] "Date"                                       
 [4] "Time"                                       
 [5] "End.time"                                   
 [6] "Surveyor"                                   
 [7] "Species"                                    
 [8] "Count"                                      
 [9] "Survey.observation.photos"                  
[10] "Animal.id"                                  
[11] "Utm.zone"                                   
[12] "Easting"                                    
[13] "Northing"                                   
[14] "Comments"                                   
[15] "Inventory.method"                           
[16] "Spatial.accuracy..m."                       
[17] "Detect.type"                                
[18] "Detect.direction..deg."                     
[19] "Detect.distance..m."                        
[20] "Temporary.animal.id"                        
[21] "Life.stage"                                 
[22] "Sex"                                        
[23] "Behaviour"                                  
[24] "Feature.type"                               
[25] "Feature.label"                              
[26] "Feature.count"                              
[27] "Sign.type"                                  
[28] "Sign.or.sample.age"                         
[29] "Sign.count"                                 
[30] "Group.label"                                
[31] "Adult.males"                                
[32] "Adult.females"                              
[33] "Adults...unclassified.sex"                  
[34] "Juvenile.males"                             
[35] "Juvenile.females"                           
[36] "Juveniles...unclassified.sex"               
[37] "Males...unclassified.life.stage"            
[38] "Females...unclassified.life.stage"          
[39] "Unclassified.life.stage.and.sex"            
[40] "Eggs"                                       
[41] "Egg.masses"                                 
[42] "Larvae"                                     
[43] "Pupae"                                      
[44] "Hatchlings"                                 
[45] "Fledglings"                                 
[46] "Add.your.new.field.here"                    
[47] "Traps.sprung"                               
[48] "No.of.visits.or.samples"                    
[49] "Nights.trapped"                             
[50] "Distance.covered..km."                      
[51] "Design.component.visit.comments"            
[52] "Design.component.visit.photos"              
[53] "Design.component.visit.photo.comments"      
[54] "Sampling.condition.type"                    
[55] "Sc.datetime"                                
[56] "Air.temp..c."                               
[57] "Prec.48.hr.air.temp..c."                    
[58] "Wind.speed"                                 
[59] "Wind.direction"                             
[60] "Prec.48.hr.wind.speed"                      
[61] "Current.precipitation"                      
[62] "Rainfall.over.24.hours..mm."                
[63] "Rainfall.over.48.hours..mm."                
[64] "Prec.48.hr.precip"                          
[65] "Cloud.type"                                 
[66] "Cloud.cover"                                
[67] "Cloud.ceiling"                              
[68] "Prec.48.hr.cloud.cover"                     
[69] "Snow.depth"                                 
[70] "Snow.cover"                                 
[71] "Time.since.5.cm.snow"                       
[72] "Water.temperature..c."                      
[73] "Sea.wind.condition"                         
[74] "Sea.surface.temperature..c."                
[75] "Sea.surface.salinity..ppt."                 
[76] "Swell.height..m."                           
[77] "Wavelet.height..cm."                        
[78] "Tide.direction"                             
[79] "Ground.temperature..c."                     
[80] "Ground.moisture"                            
[81] "Leaf.moisture"                              
[82] "Official.sunrise"                           
[83] "Lunar.phase"                                
[84] "Turbidity..cm."                             
[85] "Temperature.variance"                       
[86] "Sampling.condition.comments"                
[87] "workbook"                                   
[88] "Reliable.observer"                          
[89] "Quality.observation"                        
[90] "Additional.notes"                           
[91] "Transect.label"                             
[92] "Additional.predefined.transect.visit.fields"
[93] "Predefined.sampling.condition.fields"       
[94] "Description.precipitation"                  </code></pre>
</div>
</div>
</section>
<section id="dates-converted-to-standardized-form" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="dates-converted-to-standardized-form"><span class="header-section-number">2.2</span> Dates converted to standardized form</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>

The number of records by year are </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                     Year
Study.area.name                       2013 2014 2015 2016 2017 2019 2020
  Yellow Point Bog Ecological Reserve   27   44  153   55  127   93    2</code></pre>
</div>
</div>
</section>
<section id="checking-study-area-name" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="checking-study-area-name"><span class="header-section-number">2.3</span> Checking Study Area Name</h2>
<p>The Study Area Name should be recorded consistently across years, otherwise it may indicate that different sites are being studies. The study area name is converted to Title Case.</p>
<p>The list of Study Area Names by year in the data is:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                     Year
Study.area.name                       2013 2014 2015 2016 2017 2019 2020
  Yellow Point Bog Ecological Reserve   27   44  153   55  127   93    2</code></pre>
</div>
</div>
</section>
<section id="checking-station-codes" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="checking-station-codes"><span class="header-section-number">2.4</span> Checking Station codes</h2>
<p>While these are not used in the analysis, these labels should be consistent over time:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                     Sample.station.label
Study.area.name                       Obs Pt East Obs Pt West Res 1 &lt;NA&gt;
  Yellow Point Bog Ecological Reserve         210         193     3   95</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Year
Sample.station.label 2013 2014 2015 2016 2017 2019 2020
         Obs Pt East    7   21   50   46   86    0    0
         Obs Pt West   19   23  103    9   39    0    0
         Res 1          1    0    0    0    2    0    0
         &lt;NA&gt;           0    0    0    0    0   93    2</code></pre>
</div>
</div>
</section>
<section id="checking-species-code" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="checking-species-code"><span class="header-section-number">2.5</span> Checking species code</h2>
<p>The species code should be the same across the file.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>               Year
Species         2013 2014 2015 2016 2017 2019 2020
  ANATIDAE         3    1    0    0    0    3    0
  ANSERIFORMES     0    0    2    4    5    0    0
  B-BAGO           1    0    0    0    0    0    0
  B-BEKI           0    0    1    0    0    0    0
  B-BUFF           0    9   11    4    1    2    0
  B-BWTE           0    0    0    0    2    0    0
  B-CAGO           2    0   20    3    3    2    0
  B-CITE           0    0    0    0    1    0    0
  B-COME           0    3    6    1    1    2    0
  B-EAGR           0    0    0    0    5    0    0
  B-GBHE           0    2    2    1    0    0    0
  B-GRSC           0    1    0    0    1    0    0
  B-GWTE           0    0    0    1    2    0    0
  B-HOME          12   14   30   17   24   17    0
  B-LESC           2    0   14    0   12    0    0
  B-MALL           4    3   16    4   18   10    1
  B-NOPI           0    0    0    0    1    0    0
  B-PBGR           0    0    0    0    9    2    0
  B-RBME           0    0    0    0    0    1    0
  B-RNDU           0    2   12    2   13   15    0
  B-RNGR           0    0    0    7    0    0    0
  B-TRUS           0    1    1    0    3    0    0
  B-WODU           0    0    6    1    1    2    0
  Bucephala        0    0    0    0    0    1    0
  BUCEPHALA        0    1    0    0    0    0    0
  NULL             3    7   32   10   25   35    1
  PODICIPEDIDAE    0    0    0    0    0    1    0</code></pre>
</div>
</div>
<div class="cell">

</div>
</section>
</section>
<section id="single-site-analysis" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Single Site Analysis</h1>
<p>Date for the Yellow Point are available from 2013 to 2020.</p>
<p>This design has multiple stations that are repeatedly measured over time with multiple measurements at each station Please refer to the Fitting Trends with Complex Study Designs document in the CommonFile directory for information on fitting trends with complex study designs.</p>
<p>All analyses were done using the R (R Core Team, 2022) analysis system. All plots are also saved as separate *png files for inclusion into other reports.</p>
<div class="cell">

</div>
<section id="maximum-counts" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="maximum-counts"><span class="header-section-number">3.1</span> Maximum counts</h2>
<p>The data is first summarized to the date level by summing the count over multiple records (the different species) for each date-sample station combination. This reduces the data to one measurement per date per site/year.</p>
<p>A preliminary plot of the total count is found in <a href="#fig-wf-prelim">Figure&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wf-prelim" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="waterfowl-single-site_files/figure-html/fig-wf-prelim-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Summary plot of the data. Data is plotted on the logarithmic scale because of the wide range of values. Because of potential zeros in the data, 0.5 was added to all points only for plotting purposes.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Notice that there is a definite station effect, where, for example, the number of birds at certain stations are generally higher than at the other stations because of local station-specific conditions (e.g.&nbsp;better habitat).</p>
<p>Next the maximum count in each month in each station (but only November, December, January, and February) is found and plotted in <a href="#fig-wf-prelim2">Figure&nbsp;2</a>. As noted earlier, a better measure may be the median count rather than the mean count. The analysis would proceed in a similar fashion.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wf-prelim2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="waterfowl-single-site_files/figure-html/fig-wf-prelim2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 2: Plot of the maximum count in each station in November through February. Data is plotted on the logarithmic scale because of the wide range of values. Because of potential zeros in the data, 0.5 was added to all points only for plotting purposes.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Again there is evidence of a station effect. A month effect is less clear.</p>
<p>Because this is count data, so a linear mixed model is fit to the logarithm of the maximum call in each month at each transect in each year. The model is:</p>
<p><span class="math display">\[log(MaxCount) = Year + MonthF+StationF(R) +YearF(R)\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(log(MaxCount)\)</span> is logarithm of the maximum count at that station in that month in that year;</li>
<li><span class="math inline">\(StationF\)</span> represents the station effect;</li>
<li><span class="math inline">\(YearF\)</span> represents the year-specific effects (process error), and</li>
<li><span class="math inline">\(Year\)</span> represents the calendar year trend over time.</li>
</ul>
<p>The <span class="math inline">\(StationF\)</span> term allows for the fact that station-specific conditions may tend to affect the counts on this station consistently over time. The <span class="math inline">\(YearF\)</span> term represent the year-specific effects (process error) caused by environmental factors (e.g., a warmer than normal year may elicit more visits from waterfowl).</p>
<p>This model implicitly assumes that the trend in Nov, Dec, Jan and February are the same but with a different intercept (i.e.&nbsp;parallel lines on the logarithmic scale).</p>
<p>Model fit on the logarithmic scale assume that effects are multiplicative over time, so that the when the actual fit is done on the logarithmic scale, the trends are linear. For example, a trend may assume that there is constant 5% change over time rather than a fixed 1 unit change per year. Some caution is needed if any of the values are 0 as log(0) is not defined. In these cases, a small constant (typically ½ of the smallest positive value in the dataset) is added to all values before the analysis proceeds.</p>
<p>This model is fit using the <em>lmer()</em> function in the lmerTest package (Kuznetsova, et al.&nbsp;2016)</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Model failed to converge with 1 negative eigenvalue: -3.7e-02</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Kenward-Roger's method
        Sum Sq Mean Sq NumDF   DenDF F value Pr(&gt;F)
Year   0.01488 0.01488     1  2.3106  0.0146 0.9134
MonthF 1.35044 0.45015     3 18.7228  0.4418 0.7258</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: log(max.count + 0.5) ~ Year + MonthF + (1 | Sample.station.labelF) +  
    (1 | YearF)
   Data: count.max

REML criterion at convergence: 71.2

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-2.2527 -0.2805  0.1165  0.6867  1.3172 

Random effects:
 Groups                Name        Variance Std.Dev.
 YearF                 (Intercept) 0.00037  0.01924 
 Sample.station.labelF (Intercept) 0.00000  0.00000 
 Residual                          1.01591  1.00793 
Number of obs: 26, groups:  YearF, 5; Sample.station.labelF, 2

Fixed effects:
             Estimate Std. Error        df t value Pr(&gt;|t|)
(Intercept) -43.06502  299.92797   5.09804  -0.144    0.891
Year          0.02213    0.14884   5.09892   0.149    0.887
MonthF2       0.05553    0.58193  19.81356   0.095    0.925
MonthF11      0.39307    0.56484  20.98595   0.696    0.494
MonthF12      0.59951    0.56079  20.50987   1.069    0.297

Correlation of Fixed Effects:
         (Intr) Year   MnthF2 MntF11
Year     -1.000                     
MonthF2  -0.001  0.000              
MonthF11 -0.120  0.119  0.515       
MonthF12 -0.007  0.006  0.519  0.535
optimizer (nloptwrap) convergence code: 0 (OK)
boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups                Name        Std.Dev.
 YearF                 (Intercept) 0.019237
 Sample.station.labelF (Intercept) 0.000000
 Residual                          1.007925</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                         Study.area.name      slope  slope.se   p.value
Year Yellow Point Bog Ecological Reserve 0.02213323 0.8874857 0.8874857</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                      Study.area.name   Year MonthF pred.mean
1 Yellow Point Bog Ecological Reserve 2013.0      1  4.433407
2 Yellow Point Bog Ecological Reserve 2013.1      1  4.443230
3 Yellow Point Bog Ecological Reserve 2013.2      1  4.453076
4 Yellow Point Bog Ecological Reserve 2013.3      1  4.462943
5 Yellow Point Bog Ecological Reserve 2013.4      1  4.472831
6 Yellow Point Bog Ecological Reserve 2013.5      1  4.482742</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-max-trend" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="waterfowl-single-site_files/figure-html/fig-max-trend-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 3: Summary plot of the trend in maximum birds counts. Because the model was fit on the logarithmic scale, the fitted trend line is not a straight line but curved.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><a href="#fig-max-trend">Figure&nbsp;3</a> shows a summary plot, along with estimates of the slope, its standard error, and the p-value of the hypothesis of no trend. With 7 years of data, the estimated slope is 0.022 (SE 0.149) /year (p = 0.913).</p>
<p>The reported common slope is on the logarithmic scale. This corresponds to an approximate exp(0.022)=1.02x multiplicative change/year, i.e.&nbsp;the mean maximum count in year <span class="math inline">\(t+1\)</span> is about 1.02x the mean maximum count in year <span class="math inline">\(t\)</span>. Because the analysis is done on the logarithmic scale, the fitted trend line will look non-linear on the original (non-transformed) scale.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-count-max-resid" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="waterfowl-single-site_files/figure-html/fig-count-max-resid-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 4: Model fit diagnostic plots from trend in maximum count</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Residual plots are presented in (<a href="#fig-count-max-resid">Figure&nbsp;4</a>). In the upper left corner is a plot of residuals vs.&nbsp; the fitted values. A good plot will show a random scatter around 0. Any large deviations from 0 should be investigated as potential outliers. In the upper right is a normal probability plot. Points should be close to the dashed reference line. Fortunately, the analysis is fairly robust against non-normality so only extreme departures are worrisome. The bottom left plot shows that the year specific effects are very small (the dots are all close to 0). The bottom right plot shows that the station effects with some stations tending to have higher counts than other stations.</p>
<div class="cell">

</div>
<p>Whenever an analysis of a trend over time is conducted, the analysis should test and adjust for autocorrelation. Autocorrelation usually isn’t a problem (and likely cannot be detected) unless you have 10+ years of data. The test for autocorrelation commonly used is the Durbin-Watson test and we find ( for the test of no autocorrelation.</p>
<p>The analysis of the median count per month would follow the same steps as shown above and the R code is easy to modify. Similarly, this analysis was conducted at the total count level (over all species) b ut could be done for individual species. One potential problem is that in some cases, species information is only recorded at the Genus or higher level. In these case, this data will have to discarded when the analysis is done at the species level, but then you are making an implicit assumption that recording at the Genus level happens at random and is unrelated to the response. If this assumption is violated (e.g.&nbsp;perhaps when there are larger number of birds, it is too difficult to record at the individual species level) then this is not occurring at random and some effort must be made to “split” the genus level information among the species.</p>
<p>Trends over time could also occur in the diversity of the birds. In theory, standard diversity measures could be used and tracked over time, but these have a very strong assumption that all species are equally detectable by the observer. This is unlikely to be true. Secondly, the actual counts are quite small, and diversity measures that rely on actual counts (e.g.&nbsp;Simpson’s diversity) will not perform well. For this reason, I do not recommend an analysis on the diversity of the observations.</p>
</section>
</section>
<section id="summary" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Summary</h1>
<p>Some caution is required to ensure that all stations are visited equally often in a year. In this balanced design, it is straightforward to compute statistics over all measurements of a station in a month and all stations in a year have the same number of visits. It is possible to modify the analysis if only some stations are visited on a particular date with an unequal number of visits to a station in a year. A simple way to deal with unbalance would be to delete some of the observations, but better methods are available.</p>
<p>The protocol assumes that the observation points allow the observer to see all the waterfowl on the wetland between them so differential coverage over time may not be a problem.</p>
</section>
<section id="references" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> References</h1>
<p>Kuznetsova A, Brockhoff PB, Christensen RHB (2017). lmerTest Package: Tests in Linear Mixed Effects Models. Journal of Statistical Software, 82, 1-26. doi:10.18637/jss.v082.i13</p>
<p>R Core Team (2022). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. https://www.R-project.org/.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>